url: "https://robot-dreams-de-api.herokuapp.com"
username: "rd_dreams"
password: "djT6LasE"
endpoint: "/out_of_stock"
file_name: "currency.json"
output_directory: "./data"
content_type: "application/json"